### ISSUE TITLE
Difference between normal and 16 variant

### ISSUE THREAD

**Issue by 3N4N** [afq984/base16-xfce4-terminal#6]
Why are there two versions of similar colorschemes?

**Comment by 3N4N** [comment]
@afq984, do you not check your Github issues?

**Comment by afq984** [comment]
Sorry, I somehow missed the notification mail.

The two versions use two different mappings. The `.16` variant uses all 16 colors for all color tags, while the default variant uses only a subset of it.
This is done because programs and theme designers do not agree on what some color codes should refer to.
See the example below, xfce4-terminal expects two kinds of "Green" to be provided, but "Default Light" only has one:
* In this case, the `.16` variant tries to use up all color provided by the theme
  ![image](https://user-images.githubusercontent.com/4318379/86017279-6e609a80-ba56-11ea-8614-bc4b5394c1f0.png)
* The default variant tries to match the color names described by `xfce4-terminal`, while not using all 16 colors provided by the theme
  ![image](https://user-images.githubusercontent.com/4318379/86017372-8c2dff80-ba56-11ea-8a45-8862a9c7405d.png)

For that reason, some themes may look better on one of the variants, so the mapping choice is left to the user.

![image](https://user-images.githubusercontent.com/4318379/86018531-1460d480-ba58-11ea-9ce6-2f9124b654a8.png)
![image](https://user-images.githubusercontent.com/4318379/86018512-0dd25d00-ba58-11ea-8984-bcf21dfb2efd.png)


Feel free to correct me if I got anything wrong, or if there's something I've done differently from common practices / base16 recommendations.

**Comment by 3N4N** [comment]
Thanks for taking the time and explaining.
